AllCops:
  Include:
    - Rakefile
    - config.ru
    - "**/*.rake"
    - "**/*.rb"
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - scratch.rb

  TargetRubyVersion: 2.5

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/api/melissa/property.rb
    - app/controllers/insured_controller.rb
    - app/models/property.rb
Metrics/AbcSize: # configured above
  Enabled: false # configured above
Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'app/admin/**/*.rb'
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/property.rb
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Exclude:
    - app/models/property.rb
Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName: #review
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/VariableNumber: #review
  Enabled: false

Performance/Casecmp:
  Enabled: false
Performance/StringReplacement:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters: #review
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentAnnotation: #review
  Enabled: false
Style/ConditionalAssignment:  #review
  Enabled: false
Style/DateTime: #review, needs manual cleanup
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod: # review, only requires they are on 1 line.. meh!?
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause: #review, probably want, needs ton of manual cleanup
  Enabled: false
Style/IdenticalConditionalBranches: #review. Definitely want but needs manual cleanup
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate: # review. A good cop, most autocorrect but needs some manual cleanup.
  Enabled: false
Style/RaiseArgs: #review Need manual cleanup.
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray: #review, Autocorrects perfect, just not sure if we like this cop.
  Enabled: false
Style/WordArray:
  Enabled: false
