AllCops:
  Include:
    - Rakefile
    - config.ru
    - "**/*.rake"
    - "**/*.rb"
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - scratch.rb

  TargetRubyVersion: 2.5

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/CommentIndentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  CountComments: false
  Max: 60
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/property.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/models/property.rb
Metrics/LineLength:
  Max: 180
  Exclude:
    - "lib/tasks/kin.rake"

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Naming/FileName:
  Exclude:
    - app/models/filings/**/*.rb

Naming/ClassAndModuleCamelCase:
  Exclude:
    - app/models/filings/**/*.rb
